services:
  neovim:
    build:
      context: .
      dockerfile: Dockerfile
    # container_name: neovim
    image: dockerregistry.gouws.org/nvim-docker
    restart: unless-stopped
    volumes:
      - /mnt/c/Projects.Git:/mnt/c/Projects.Git
  version_latest:
    extends: neovim
    image: dockerregistry.gouws.org/nvim-docker:latest
  version_date:
    extends: neovim
    image: dockerregistry.gouws.org/nvim-docker:${BUILD_DATE}

# RUN WITH:
# sudo docker stop nvim-docker && sudo docker rm nvim-docker
# sudo docker compose build && sudo docker compose up -d
# sudo docker exec -it nvim-docker /bin/zsh

# Dockerhub: https://hub.docker.com/r/killerrat/nvim-docker
# sudo docker run -d --name nvim-docker -v /mnt/c/Projects.Git:/mnt/c/Projects.Git killerrat/nvim-docker:latest

# Albert's private repo:
# sudo docker run -d --name nvim-docker -v /mnt/c/Projects.Git:/mnt/c/Projects.Git dockerregistry-ro.gouws.org/nvim-docker:latest

