require("killerrat.plugins._packer")
require("killerrat.plugins._colors")
require("killerrat.plugins._whitespace-nvim")
require("killerrat.plugins._telescope-nvim")
require("killerrat.plugins._nerdtree")
require("killerrat.plugins._harpoon")
require("killerrat.plugins._better-escape-nvim")
require("killerrat.plugins._hop")
