require("killerrat.plugins._packer")
require("killerrat.plugins._colors")
require("killerrat.plugins._whitespace-nvim")
require("killerrat.plugins._telescope-nvim")
require("killerrat.plugins._nerdtree")
require("killerrat.plugins._harpoon")
require("killerrat.plugins._better-escape-nvim")
require("killerrat.plugins._hop")
require("killerrat.plugins._nvim-surround")
require("killerrat.plugins._vim-fugitive")
require("killerrat.plugins._vim-commentary")
require("killerrat.plugins._substitute-nvim")
require("killerrat.plugins._copilot")
require("killerrat.plugins._switch-vim")
require("killerrat.plugins._lualine-nvim")
require("killerrat.plugins._bufferline-nvim")

